name: Build and test symengine
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    name: "${{ matrix.BUILD_TYPE }}-${{ matrix.OS }}-${{ matrix.CC }} (${{ toJSON(matrix) }})"
    strategy:
      fail-fast: false
      matrix:
        include:
          # Release build (latest pre-release of LLVM)
          - BUILD_TYPE: Release
            OS: ubuntu-24.04
            CC: clang
            WITH_LLVM: "LATEST"
            EXTRA_APT_REPOSITORY: 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble main'
            EXTRA_APT_PACKAGES: llvm clang lldb lld clangd libllvmlibc-20-dev

    env:
      USE_GLIBCXX_DEBUG: ${{ matrix.USE_GLIBCXX_DEBUG }}
      WITH_MPFR: ${{ matrix.WITH_MPFR }}
      WITH_LLVM: ${{ matrix.WITH_LLVM }}
      WITH_BENCHMARKS: ${{ matrix.WITH_BENCHMARKS }}
      WITH_BENCHMARKS_GOOGLE: ${{ matrix.WITH_BENCHMARKS_GOOGLE }}
      WITH_SYMENGINE_RCP: ${{ matrix.WITH_SYMENGINE_RCP }}
      TEST_IN_TREE: ${{ matrix.TEST_IN_TREE }}
      WITH_SYMENGINE_THREAD_SAFE: ${{ matrix.WITH_SYMENGINE_THREAD_SAFE }}
      WITH_PRIMESIEVE: ${{ matrix.WITH_PRIMESIEVE }}
      INTEGER_CLASS: ${{ matrix.INTEGER_CLASS }}
      WITH_ARB: ${{ matrix.WITH_ARB }}
      WITH_PIRANHA: ${{ matrix.WITH_PIRANHA }}
      CONDA_ENV_FILE: ${{ matrix.CONDA_ENV_FILE }}
      WITH_BFD: ${{ matrix.WITH_BFD }}
      WITH_FLINT: ${{ matrix.WITH_FLINT }}
      EXTRA_APT_REPOSITORY: ${{ matrix.EXTRA_APT_REPOSITORY }}
      EXTRA_APT_PACKAGES: ${{ matrix.EXTRA_APT_PACKAGES }}
      TEST_CLANG_FORMAT: ${{ matrix.TEST_CLANG_FORMAT }}
      WITH_ECM: ${{ matrix.WITH_ECM }}
      WITH_LATEST_GCC: ${{ matrix.WITH_LATEST_GCC }}
      OS: ${{ matrix.OS }}
      WITH_FLINT_DEV: ${{ matrix.WITH_FLINT_DEV }}
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      WITH_COTIRE: ${{ matrix.WITH_COTIRE }}
      WITH_COVERAGE: ${{ matrix.WITH_COVERAGE }}
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      WITH_SANITIZE: ${{ matrix.WITH_SANITIZE }}
      WITH_MPC: ${{ matrix.WITH_MPC }}
      BUILD_SHARED_LIBS: ${{ matrix.BUILD_SHARED_LIBS }}
      OPTIONS: ${{ matrix.BUILD_TYPE }}-${{ matrix.OS }}-${{ matrix.CC }}-${{ matrix.USE_GLIBCXX_DEBUG }}-${{ matrix.WITH_MPFR }}-${{ matrix.WITH_LLVM }}-${{ matrix.WITH_BENCHMARKS }}-${{ matrix.WITH_BENCHMARKS_GOOGLE }}-${{ matrix.WITH_SYMENGINE_RCP }}-${{ matrix.TEST_IN_TREE }}-${{ matrix.WITH_SYMENGINE_THREAD_SAFE }}-${{ matrix.WITH_PRIMESIEVE }}-${{ matrix.INTEGER_CLASS }}-${{ matrix.WITH_ARB }}-${{ matrix.WITH_PIRANHA }}-${{ matrix.CONDA_ENV_FILE }}-${{ matrix.WITH_BFD }}-${{ matrix.WITH_FLINT }}-${{ matrix.TEST_CLANG_FORMAT }}-${{ matrix.WITH_ECM }}-${{ matrix.WITH_LATEST_GCC }}-${{ matrix.WITH_FLINT_DEV }}-${{ matrix.WITH_COTIRE }}-${{ matrix.WITH_COVERAGE }}-${{ matrix.WITH_SANITIZE }}-${{ matrix.WITH_MPC }}-${{ matrix.BUILD_SHARED_LIBS }}
      CCACHE_DIR: 'D:\a\_temp\msys\msys64\home\runneradmin\.ccache'

    steps:
    - name: Setup msys2
      uses: msys2/setup-msys2@v2
      if: matrix.MSYSTEM != ''
      with:
        msystem: ${{ matrix.MSYSTEM }}
        update: true
        install: mingw-w64-${{ matrix.ARCH }}-gcc mingw-w64-${{ matrix.ARCH }}-cmake mingw-w64-${{ matrix.ARCH }}-ccache python make git

    - name: Set ccache dir
      if: matrix.MSYSTEM == ''
      run: echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.job }}-${{ env.OPTIONS }}-${{ runner.os }}-${{ github.sha }}
        restore-keys: ccache-${{ github.job }}-${{ env.OPTIONS }}-${{ runner.os }}-

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Build and test symengine
      shell: msys2 {0}
      if: matrix.MSYSTEM != ''
      run: |
        source bin/test_symengine_unix.sh

    - name: Build and test symengine
      shell: bash
      if: matrix.MSYSTEM == ''
      run: |
        source bin/test_symengine_unix.sh
