name: Code coverage 2
on: [push, pull_request]

jobs:
  coverage2:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Build and test symengine
      shell: bash
      run: |
        source bin/test_symengine_unix.sh
      env:
        BUILD_TYPE: Debug
        WITH_BFD: yes
        WITH_COVERAGE: yes
        TEST_IN_TREE: yes
        WITH_FLINT: yes
        WITH_FLINT_DEV: yes
        WITH_MPC: yes
        BUILD_BENCHMARKS: no
        MAKEFLAGS: -j2
        CC: gcc
        OS: ubuntu-16.04